version: '3'

services:
  web:
    image: nginx
    volumes:
    - ./nginx:/etc/nginx/conf.d/:ro
    - ./slides-dist:/usr/share/nginx/html
    ports:
    - "8080:80"
    - "8081:81"
    environment:
    - NGINX_PORT=80

  slides:
    build: .
    volumes:
    - ./slides-dist:/app/dist
    depends_on:
      - web